### ISSUE TITLE
How to reach page 1?

### ISSUE THREAD

**Issue by davidyell** [World-Architects/cakephp-query-param-preserver#6]
## What I did
Added the component to my paginated index

## What happened
If you browse to a page, the page is saved in the session, because it's a query param. Which means that when you try and reach page 1, which has no query params, the component will try and re-apply the previously saved params.

This use-case doesn't happen if you other other query params, such as sorting.

## What I expected to happen
I would expect to end up back on page 1

## What actually happened
The query params were restored and I ended up back on the page I was on before trying to reach page 1

**Comment by burzum** [comment]
@davidyell could you provide an unit test that shows the problem?

**Comment by burzum** [comment]
@davidyell this is a non-issue. Please read the [readme.md](https://github.com/World-Architects/cakephp-query-param-preserver#setup). It tells you to deactivate the page param. ;)

```php
    // You want to ignore the page param on pages with pagination
    'ignoreParams' => [
        'page'
    ]
```

**Comment by davidyell** [comment]
Ah, perhaps I missed this when I set it up. Thanks for the reply
